# roles/mariadb/tasks/init_mariadb.yml
---

- name: Copy sql init scripts
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item|basename }}"
    mode: '0600'
  with_items: "{{ mariadb_init_scripts }}"
  tags: mariadb

- name: Initialise mariadb
  command: "mysql --user=root --password={{ mariadb_root_password }} -e 'source /tmp/{{ item|basename }};'"
  with_items: "{{ mariadb_init_scripts }}"
  tags: mariadb

- name: Delete init scripts from the server
  file:
    name: "/tmp/{{ item|basename }}"
    state: absent
  with_items: "{{ mariadb_init_scripts }}"
  tags: mariadb
